import { 
  ArrowRight, 
  ChevronRight, 
  Code, 
  Code2Icon, 
  Copy, 
  Download, 
  ExternalLink, 
  FileCode, 
  Github, 
  Loader2, 
  Menu, 
  MessageSquare, 
  Moon, 
  MoreHorizontal, 
  Plus, 
  Save, 
  Settings, 
  Share2, 
  Sun, 
  Terminal, 
  User, 
  Users, 
  X, 
  Zap
} from "lucide-react";

export const Icons = {
  logo: Zap,
  menu: Menu,
  close: X,
  spinner: Loader2,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  add: Plus,
  code: Code,
  terminal: Terminal,
  file: FileCode,
  user: User,
  team: Users,
  message: MessageSquare,
  settings: Settings,
  moon: Moon,
  sun: Sun,
  copy: Copy,
  save: Save,
  share: Share2,
  more: MoreHorizontal,
  download: Download,
  github: Github,
  codeEditor: Code2Icon,
  externalLink: ExternalLink,
};